package se.ltu.eduo.collection.mapper;

import org.mapstruct.*;
import se.ltu.eduo.collection.dto.CollectionDto;
import se.ltu.eduo.collection.dto.GenerationDto;
import se.ltu.eduo.collection.request.CreateGenerationRequest;
import se.ltu.eduo.collection.model.Generation;
import se.ltu.eduo.collection.model.GenerationSourceMaterial;
import se.ltu.eduo.collection.model.Quiz;

@Mapper(unmappedTargetPolicy = ReportingPolicy.WARN, componentModel = MappingConstants.ComponentModel.SPRING)
public interface GenerationMapper {
    // tell MapStruct to ignore these fields when mapping from DTO to entity, 
    // because they are not provided by the client but set by the service layer (
    // or in the case of Quiz.generation, set by @AfterMapping linkQuiz below).
    // "collection" is a JPA relationship set by the service layer after mapping (requires entity lookup).
    // "generation" on the nested Quiz is a back-reference wired by @AfterMapping linkQuiz below.
    @Mapping(target = "collection", ignore = true)
    @Mapping(target = "quiz.generation", ignore = true)
    @Mapping(target = "sourceMaterials", ignore = true)
    Generation toEntity(GenerationDto generationDto);

    //för mapping av CreateGenerationRequest till Generation i createGeneration
    @Mapping(target = "collection", ignore = true)    // set by service layer after mapping
    @Mapping(target = "sourceMaterials", ignore = true)
    @Mapping(target = "id", ignore = true)            // UUID generated by JPA on persist
    @Mapping(target = "createdAt", ignore = true)     // set by @CreationTimestamp
    @Mapping(target = "updatedAt", ignore = true)     // set by @UpdateTimestamp
    @Mapping(target = "quiz", ignore = true)          // does not exist at creation time; created after LLM responds
    Generation toEntity(CreateGenerationRequest request);

    @AfterMapping
    default void linkSourceMaterials(@MappingTarget Generation generation)
    {
        generation.getSourceMaterials()
                  .forEach(sourceMaterial -> sourceMaterial.setGeneration(generation));
    }

    @AfterMapping
    default void linkQuiz(@MappingTarget Generation generation)
    {
        Quiz quiz = generation.getQuiz();
        if (quiz != null)
        {
            quiz.setGeneration(generation);
        }
    }

    @Mapping(target = "collectionId", source = "collection.id")
    GenerationDto toDto(Generation generation);

    @Mapping(target = "id", source = "sourceMaterial.id")
    @Mapping(target = "filename", source = "sourceMaterial.filename")
    @Mapping(target = "fileType", source = "sourceMaterial.fileType")
    @Mapping(target = "fileSizeBytes", source = "sourceMaterial.fileSizeBytes")
    @Mapping(target = "uploadedAt", source = "sourceMaterial.uploadedAt")
    CollectionDto.SourceMaterialDto toDto(GenerationSourceMaterial gsm);

    // Same rationale as toEntity(GenerationDto): "collection" is owned by the service layer,
    // and Quiz.generation is a back-reference handled by @AfterMapping linkQuiz.
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "collection", ignore = true)
    @Mapping(target = "quiz.generation", ignore = true)
    @Mapping(target = "sourceMaterials", ignore = true)
    Generation partialUpdate(GenerationDto generationDto, @MappingTarget Generation generation);
}